name: monkey_shell
description: A simple shell for the Monkey programming language.
version: 0.9.0
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  monkey_lang: ^0.9.6
  html: ^0.13.1
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- dart_to_js_script_rewriter
